[package]
name = "creating-a-string"
version = "0.1.0"
authors = ["server"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
